spring:
  application:
    name: springboot-hibernate-sample

dataSource:
  maxActive: 100
  maxIdle: 30
  maxWait: 10000
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/sample?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true
  username: root
  password: root
  validationQuery: select 1

hibernate:
  scanPackages: com.rx
  dialect: org.hibernate.dialect.MySQLDialect
  show_sql: false
  format_sql: false
  use_sql_comments: true
  hbm2ddl:
    auto: none
  cache:
    use_query_cache: false
    use_second_level_cache: false  